test_queries: data/Fold1/test.txt
training_queries: data/Fold1/train.txt
feature_count: 64 # 64 for .Gov, 46 for MQ*, 136 for MSLR
num_runs: 5
num_queries: 1000
processes: 1
query_sampling_method: random
user_model: environment.CascadeUserModel
# for p-click and p-stop provide mappings from relevance grades to probabilities
user_model_args: --p_click 0:0.0,1:0.5,2:1 --p_stop 0:0.0,1:0.0,2:0.0
system: retrieval_system.PerturbationLearningSystem
system_args:
    --init_weights zero # for 3PR weights should be initialised with zero
    --ranker ranker.DeterministicRankingFunction
    --ranker_arg 3
    --ranker_tie random
    --perturbator perturbation.ProbabilisticPerturbator

output_dir: Perterperter
output_dir_overwrite: True
output_prefix: Fold1

evaluation:
    - evaluation.NdcgEval
experimenter: experiment.LearningExperiment
