num_runs: 500
num_queries: 500
result_length: 10
num_relevant: 1-3
experimenter: experiment.VASyntheticComparisonExperiment
user_model: environment.FederatedClickModel
# binary perfect:
user_model_args: "-"
# binary navigational:
#user_model_args: "--p_click 0:0.05, 1:0.8 --p_stop 0:.0, 1:0.8"
# binary informational:
#user_model_args: "--p_click 0:0.4, 1:0.9 --p_stop 0:0.1, 1:0.5"
# binary almost random:
#user_model_args: "--p_click 0:0.4, 1:0.6 --p_stop 0:0.5, 1:0.5"
# binary random:
#user_model_args: "--p_click 0:0.5, 1:0.5 --p_stop 0:.0, 1:.0"
# method names have to be unique
evaluation_methods:
- BI
- TD
#- DC-1
#- DC-2
# - DC-3
# normal PI
#- PI-expectation-0.5
#- PI-expectation-0.8
#- PI-expectation-1-without-marginal
#- PI-expectation-2-without-marginal
#- PI-expectation-3-without-marginal
#- PI-expectation-1
#- PI-expectation-2
#- PI-expectation-3
#- PI-expectation-5
#- PI-expectation-10
# PI with deterministic interleaving but normal comparison
#- PI-det-0.5
#- PI-det-0.8
#- PI-det-1
#- PI-det-2
#- PI-det-3
#- PI-det-5
#- PI-det-10
#- PI-binary
# PI with deterministic interleaving and comparison, with and without marginalization
#- PI-det-with-marginal
#- PI-det-without-marginal
- VA
evaluation_methods_args:
- "--class_name comparison.BalancedInterleave --ranker det --ranker_args None --startinglist random"
- "--class_name comparison.TeamDraft --ranker det --ranker_args None"
#- "--class_name comparison.DocumentConstraints --ranker det --ranker_args None --startinglist random --constraints 1"
#- "--class_name comparison.DocumentConstraints --ranker det --ranker_args None --startinglist random --constraints 2"
#- "--class_name comparison.DocumentConstraints --ranker det --ranker_args None --startinglist random --constraints 3"
# normal PI
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 0.5 --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 0.8 --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 1 --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 2 --aggregate expectation"
# - "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 3 --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 1 --aggregate expectation --compare_td 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 2 --aggregate expectation --compare_td 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 3 --aggregate expectation --compare_td 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 5 --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 10 --aggregate expectation"
# PI with deterministic interleaving but normal comparison
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 0.5 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 0.8 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 1 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 2 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 3 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 5 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 10 --aggregate expectation --det_interleave 1"
#- "--class_name comparison.ProbabilisticInterleave --ranker prob --ranker_args 3 --aggregate binary"
# PI with deterministic interleaving and comparison, with and without marginalization
#- "--class_name comparison.ProbabilisticInterleave --ranker det --ranker_args None --aggregate expectation"
#- "--class_name comparison.ProbabilisticInterleave --ranker det --ranker_args None --aggregate expectation --compare_td 1"
# OI
#- "--class_name comparison.OptimizedInterleave ranker_args None --credit linear_credit"
# TdiVa
- "--class_name comparison.TdiVa1  --ranker det --ranker_args None"

run_start_id: 0
output_dir: /Users/aschuth/experiments/online_evaluation/synthetic-500-samevert
output_prefix: evaluation-synthetic-500
output_dir_overwrite: 1

