test_queries: ./data/Webscope_C14B/ltrc_yahoo/set1.test.txt
training_queries: ./data/Webscope_C14B/ltrc_yahoo/set1.train.txt
feature_count: 700 # 64 for .Gov, 46 for MQ*, 136 for MSLR
num_runs: 2
# 1017 = Exactly the number of queries in MQ2007 Fold 1
# 6000 = Exactly the number of queries in MSLR-WEB10K Fold 1
num_queries: 19944
processes: 1
query_sampling_method: fixed
user_model: environment.RelevantUserModel
# for p-click and p-stop provide mappings from relevance grades to probabilities
user_model_args: -limit -1
system: retrieval_system.PerturbationLearningSystem
system_args:
    --init_weights zero
    --ranker ranker.DeterministicRankingFunction
    --ranker_tie random
    --perturbator perturbation.DynamicProbabilisticPerturbator

output_dir: Datadump/D3PR
output_dir_overwrite: True
output_prefix: D3PR-Webscope-set1-run2

# Possible parameters for now:
#   - cutoff: will cut off the ranking for every eval
#             (offline/online, train/test). Not using this parameter will
#             default it to the length of the ranking
evaluation:
    - evaluation.NdcgEval cutoff 5
    - evaluation.NdcgEval cutoff 10
    - evaluation.PAKEval cutoff 1
    - evaluation.PAKEval cutoff 5
    - evaluation.PAKEval cutoff 10
experimenter: experiment.LearningExperiment
